// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.3
// source: sales/sort.proto

package sales

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortColumn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column string `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Order  string `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *SortColumn) Reset() {
	*x = SortColumn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sales_sort_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortColumn) ProtoMessage() {}

func (x *SortColumn) ProtoReflect() protoreflect.Message {
	mi := &file_sales_sort_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortColumn.ProtoReflect.Descriptor instead.
func (*SortColumn) Descriptor() ([]byte, []int) {
	return file_sales_sort_proto_rawDescGZIP(), []int{0}
}

func (x *SortColumn) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *SortColumn) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type SortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Columns []*SortColumn `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
}

func (x *SortRequest) Reset() {
	*x = SortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sales_sort_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortRequest) ProtoMessage() {}

func (x *SortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sales_sort_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortRequest.ProtoReflect.Descriptor instead.
func (*SortRequest) Descriptor() ([]byte, []int) {
	return file_sales_sort_proto_rawDescGZIP(), []int{1}
}

func (x *SortRequest) GetColumns() []*SortColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

var File_sales_sort_proto protoreflect.FileDescriptor

var file_sales_sort_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x2f, 0x73, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x0a, 0x53, 0x6f, 0x72,
	0x74, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x3a, 0x0a, 0x0b, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x2e, 0x53, 0x6f,
	0x72, 0x74, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sales_sort_proto_rawDescOnce sync.Once
	file_sales_sort_proto_rawDescData = file_sales_sort_proto_rawDesc
)

func file_sales_sort_proto_rawDescGZIP() []byte {
	file_sales_sort_proto_rawDescOnce.Do(func() {
		file_sales_sort_proto_rawDescData = protoimpl.X.CompressGZIP(file_sales_sort_proto_rawDescData)
	})
	return file_sales_sort_proto_rawDescData
}

var file_sales_sort_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sales_sort_proto_goTypes = []interface{}{
	(*SortColumn)(nil),  // 0: sales.SortColumn
	(*SortRequest)(nil), // 1: sales.SortRequest
}
var file_sales_sort_proto_depIdxs = []int32{
	0, // 0: sales.SortRequest.columns:type_name -> sales.SortColumn
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sales_sort_proto_init() }
func file_sales_sort_proto_init() {
	if File_sales_sort_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sales_sort_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortColumn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sales_sort_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sales_sort_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sales_sort_proto_goTypes,
		DependencyIndexes: file_sales_sort_proto_depIdxs,
		MessageInfos:      file_sales_sort_proto_msgTypes,
	}.Build()
	File_sales_sort_proto = out.File
	file_sales_sort_proto_rawDesc = nil
	file_sales_sort_proto_goTypes = nil
	file_sales_sort_proto_depIdxs = nil
}
