// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.3
// source: transaction/service_type.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service type item
type GetServiceTypeItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price     int64  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	CreatedBy int64  `protobuf:"varint,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedBy int64  `protobuf:"varint,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt string `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *GetServiceTypeItem) Reset() {
	*x = GetServiceTypeItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServiceTypeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceTypeItem) ProtoMessage() {}

func (x *GetServiceTypeItem) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceTypeItem.ProtoReflect.Descriptor instead.
func (*GetServiceTypeItem) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{0}
}

func (x *GetServiceTypeItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetServiceTypeItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetServiceTypeItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetServiceTypeItem) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *GetServiceTypeItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetServiceTypeItem) GetUpdatedBy() int64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *GetServiceTypeItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateServiceTypeItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price int64               `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Data  *GetServiceTypeItem `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateServiceTypeItemRequest) Reset() {
	*x = CreateServiceTypeItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServiceTypeItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceTypeItemRequest) ProtoMessage() {}

func (x *CreateServiceTypeItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceTypeItemRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceTypeItemRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{1}
}

func (x *CreateServiceTypeItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateServiceTypeItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceTypeItemRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateServiceTypeItemRequest) GetData() *GetServiceTypeItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateServiceTypeItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateServiceTypeItemResponse) Reset() {
	*x = CreateServiceTypeItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServiceTypeItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceTypeItemResponse) ProtoMessage() {}

func (x *CreateServiceTypeItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceTypeItemResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceTypeItemResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{2}
}

func (x *CreateServiceTypeItemResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateServiceTypeItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateServiceTypeItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price int64               `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Data  *GetServiceTypeItem `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateServiceTypeItemRequest) Reset() {
	*x = UpdateServiceTypeItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServiceTypeItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceTypeItemRequest) ProtoMessage() {}

func (x *UpdateServiceTypeItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceTypeItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceTypeItemRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateServiceTypeItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateServiceTypeItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServiceTypeItemRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateServiceTypeItemRequest) GetData() *GetServiceTypeItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateServiceTypeItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UpdateServiceTypeItemResponse) Reset() {
	*x = UpdateServiceTypeItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServiceTypeItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceTypeItemResponse) ProtoMessage() {}

func (x *UpdateServiceTypeItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceTypeItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateServiceTypeItemResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateServiceTypeItemResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateServiceTypeItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteServiceTypeItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteServiceTypeItemRequest) Reset() {
	*x = DeleteServiceTypeItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteServiceTypeItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceTypeItemRequest) ProtoMessage() {}

func (x *DeleteServiceTypeItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceTypeItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceTypeItemRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteServiceTypeItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteServiceTypeItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteServiceTypeItemResponse) Reset() {
	*x = DeleteServiceTypeItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteServiceTypeItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceTypeItemResponse) ProtoMessage() {}

func (x *DeleteServiceTypeItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceTypeItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceTypeItemResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteServiceTypeItemResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteServiceTypeItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EnableDisableServiceTypeItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *EnableDisableServiceTypeItemRequest) Reset() {
	*x = EnableDisableServiceTypeItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableDisableServiceTypeItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableDisableServiceTypeItemRequest) ProtoMessage() {}

func (x *EnableDisableServiceTypeItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableDisableServiceTypeItemRequest.ProtoReflect.Descriptor instead.
func (*EnableDisableServiceTypeItemRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{7}
}

func (x *EnableDisableServiceTypeItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnableDisableServiceTypeItemRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EnableDisableServiceTypeItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *EnableDisableServiceTypeItemResponse) Reset() {
	*x = EnableDisableServiceTypeItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableDisableServiceTypeItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableDisableServiceTypeItemResponse) ProtoMessage() {}

func (x *EnableDisableServiceTypeItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableDisableServiceTypeItemResponse.ProtoReflect.Descriptor instead.
func (*EnableDisableServiceTypeItemResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{8}
}

func (x *EnableDisableServiceTypeItemResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EnableDisableServiceTypeItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Service type
type CreateServiceTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutletId          int64                           `protobuf:"varint,1,opt,name=outlet_id,json=outletId,proto3" json:"outlet_id,omitempty"`
	Based             string                          `protobuf:"bytes,2,opt,name=based,proto3" json:"based,omitempty"`
	Name              string                          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                          `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Estimation        int64                           `protobuf:"varint,5,opt,name=estimation,proto3" json:"estimation,omitempty"`
	MinWeight         float32                         `protobuf:"fixed32,6,opt,name=min_weight,json=minWeight,proto3" json:"min_weight,omitempty"`
	Price             int64                           `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	OptionalItemOnAdd bool                            `protobuf:"varint,8,opt,name=optional_item_on_add,json=optionalItemOnAdd,proto3" json:"optional_item_on_add,omitempty"`
	PaymentType       string                          `protobuf:"bytes,9,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Items             []*CreateServiceTypeItemRequest `protobuf:"bytes,10,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CreateServiceTypeRequest) Reset() {
	*x = CreateServiceTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServiceTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceTypeRequest) ProtoMessage() {}

func (x *CreateServiceTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceTypeRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{9}
}

func (x *CreateServiceTypeRequest) GetOutletId() int64 {
	if x != nil {
		return x.OutletId
	}
	return 0
}

func (x *CreateServiceTypeRequest) GetBased() string {
	if x != nil {
		return x.Based
	}
	return ""
}

func (x *CreateServiceTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceTypeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateServiceTypeRequest) GetEstimation() int64 {
	if x != nil {
		return x.Estimation
	}
	return 0
}

func (x *CreateServiceTypeRequest) GetMinWeight() float32 {
	if x != nil {
		return x.MinWeight
	}
	return 0
}

func (x *CreateServiceTypeRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateServiceTypeRequest) GetOptionalItemOnAdd() bool {
	if x != nil {
		return x.OptionalItemOnAdd
	}
	return false
}

func (x *CreateServiceTypeRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *CreateServiceTypeRequest) GetItems() []*CreateServiceTypeItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateServiceTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64           `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data   *GetServiceType `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateServiceTypeResponse) Reset() {
	*x = CreateServiceTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServiceTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceTypeResponse) ProtoMessage() {}

func (x *CreateServiceTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceTypeResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceTypeResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{10}
}

func (x *CreateServiceTypeResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateServiceTypeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateServiceTypeResponse) GetData() *GetServiceType {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateServiceTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Based             string  `protobuf:"bytes,2,opt,name=based,proto3" json:"based,omitempty"`
	Name              string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description       string  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Estimation        int64   `protobuf:"varint,5,opt,name=estimation,proto3" json:"estimation,omitempty"`
	MinWeight         float32 `protobuf:"fixed32,6,opt,name=min_weight,json=minWeight,proto3" json:"min_weight,omitempty"`
	Price             int64   `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	OptionalItemOnAdd bool    `protobuf:"varint,8,opt,name=optional_item_on_add,json=optionalItemOnAdd,proto3" json:"optional_item_on_add,omitempty"`
	PaymentType       string  `protobuf:"bytes,9,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
}

func (x *UpdateServiceTypeRequest) Reset() {
	*x = UpdateServiceTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServiceTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceTypeRequest) ProtoMessage() {}

func (x *UpdateServiceTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceTypeRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateServiceTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateServiceTypeRequest) GetBased() string {
	if x != nil {
		return x.Based
	}
	return ""
}

func (x *UpdateServiceTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServiceTypeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateServiceTypeRequest) GetEstimation() int64 {
	if x != nil {
		return x.Estimation
	}
	return 0
}

func (x *UpdateServiceTypeRequest) GetMinWeight() float32 {
	if x != nil {
		return x.MinWeight
	}
	return 0
}

func (x *UpdateServiceTypeRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateServiceTypeRequest) GetOptionalItemOnAdd() bool {
	if x != nil {
		return x.OptionalItemOnAdd
	}
	return false
}

func (x *UpdateServiceTypeRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

type UpdateServiceTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64           `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data   *GetServiceType `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateServiceTypeResponse) Reset() {
	*x = UpdateServiceTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServiceTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceTypeResponse) ProtoMessage() {}

func (x *UpdateServiceTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceTypeResponse.ProtoReflect.Descriptor instead.
func (*UpdateServiceTypeResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateServiceTypeResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateServiceTypeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateServiceTypeResponse) GetData() *GetServiceType {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetServiceType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OutletId          int64                 `protobuf:"varint,2,opt,name=outlet_id,json=outletId,proto3" json:"outlet_id,omitempty"`
	Based             string                `protobuf:"bytes,3,opt,name=based,proto3" json:"based,omitempty"`
	Name              string                `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Estimation        int64                 `protobuf:"varint,6,opt,name=estimation,proto3" json:"estimation,omitempty"`
	MinWeight         float32               `protobuf:"fixed32,7,opt,name=min_weight,json=minWeight,proto3" json:"min_weight,omitempty"`
	Price             int64                 `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	OptionalItemOnAdd bool                  `protobuf:"varint,9,opt,name=optional_item_on_add,json=optionalItemOnAdd,proto3" json:"optional_item_on_add,omitempty"`
	PaymentType       string                `protobuf:"bytes,10,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	CreatedBy         int64                 `protobuf:"varint,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt         string                `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedBy         int64                 `protobuf:"varint,13,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt         string                `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Items             []*GetServiceTypeItem `protobuf:"bytes,15,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetServiceType) Reset() {
	*x = GetServiceType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServiceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceType) ProtoMessage() {}

func (x *GetServiceType) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceType.ProtoReflect.Descriptor instead.
func (*GetServiceType) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{13}
}

func (x *GetServiceType) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetServiceType) GetOutletId() int64 {
	if x != nil {
		return x.OutletId
	}
	return 0
}

func (x *GetServiceType) GetBased() string {
	if x != nil {
		return x.Based
	}
	return ""
}

func (x *GetServiceType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetServiceType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetServiceType) GetEstimation() int64 {
	if x != nil {
		return x.Estimation
	}
	return 0
}

func (x *GetServiceType) GetMinWeight() float32 {
	if x != nil {
		return x.MinWeight
	}
	return 0
}

func (x *GetServiceType) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetServiceType) GetOptionalItemOnAdd() bool {
	if x != nil {
		return x.OptionalItemOnAdd
	}
	return false
}

func (x *GetServiceType) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *GetServiceType) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *GetServiceType) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetServiceType) GetUpdatedBy() int64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *GetServiceType) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetServiceType) GetItems() []*GetServiceTypeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetServiceTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetServiceTypeRequest) Reset() {
	*x = GetServiceTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServiceTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceTypeRequest) ProtoMessage() {}

func (x *GetServiceTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceTypeRequest.ProtoReflect.Descriptor instead.
func (*GetServiceTypeRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{14}
}

func (x *GetServiceTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetServiceTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64           `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data   *GetServiceType `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetServiceTypeResponse) Reset() {
	*x = GetServiceTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServiceTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceTypeResponse) ProtoMessage() {}

func (x *GetServiceTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceTypeResponse.ProtoReflect.Descriptor instead.
func (*GetServiceTypeResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{15}
}

func (x *GetServiceTypeResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetServiceTypeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetServiceTypeResponse) GetData() *GetServiceType {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListServiceTypeFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutletId  int64   `protobuf:"varint,1,opt,name=outlet_id,json=outletId,proto3" json:"outlet_id,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MinWeight float32 `protobuf:"fixed32,3,opt,name=min_weight,json=minWeight,proto3" json:"min_weight,omitempty"`
	Price     int64   `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *ListServiceTypeFilter) Reset() {
	*x = ListServiceTypeFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListServiceTypeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceTypeFilter) ProtoMessage() {}

func (x *ListServiceTypeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceTypeFilter.ProtoReflect.Descriptor instead.
func (*ListServiceTypeFilter) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{16}
}

func (x *ListServiceTypeFilter) GetOutletId() int64 {
	if x != nil {
		return x.OutletId
	}
	return 0
}

func (x *ListServiceTypeFilter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListServiceTypeFilter) GetMinWeight() float32 {
	if x != nil {
		return x.MinWeight
	}
	return 0
}

func (x *ListServiceTypeFilter) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ListServiceTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip   int64                  `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Filter *ListServiceTypeFilter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Like   bool                   `protobuf:"varint,4,opt,name=like,proto3" json:"like,omitempty"`
	Sort   *SortRequest           `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
}

func (x *ListServiceTypeRequest) Reset() {
	*x = ListServiceTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListServiceTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceTypeRequest) ProtoMessage() {}

func (x *ListServiceTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceTypeRequest.ProtoReflect.Descriptor instead.
func (*ListServiceTypeRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{17}
}

func (x *ListServiceTypeRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListServiceTypeRequest) GetSkip() int64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListServiceTypeRequest) GetFilter() *ListServiceTypeFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListServiceTypeRequest) GetLike() bool {
	if x != nil {
		return x.Like
	}
	return false
}

func (x *ListServiceTypeRequest) GetSort() *SortRequest {
	if x != nil {
		return x.Sort
	}
	return nil
}

type ListServiceTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string            `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data   []*GetServiceType `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total  int64             `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListServiceTypeResponse) Reset() {
	*x = ListServiceTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListServiceTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceTypeResponse) ProtoMessage() {}

func (x *ListServiceTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceTypeResponse.ProtoReflect.Descriptor instead.
func (*ListServiceTypeResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{18}
}

func (x *ListServiceTypeResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListServiceTypeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListServiceTypeResponse) GetData() []*GetServiceType {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListServiceTypeResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteServiceTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteServiceTypeRequest) Reset() {
	*x = DeleteServiceTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteServiceTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceTypeRequest) ProtoMessage() {}

func (x *DeleteServiceTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceTypeRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteServiceTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteServiceTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteServiceTypeResponse) Reset() {
	*x = DeleteServiceTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteServiceTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceTypeResponse) ProtoMessage() {}

func (x *DeleteServiceTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceTypeResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceTypeResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteServiceTypeResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteServiceTypeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EnableDisableServiceTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *EnableDisableServiceTypeRequest) Reset() {
	*x = EnableDisableServiceTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableDisableServiceTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableDisableServiceTypeRequest) ProtoMessage() {}

func (x *EnableDisableServiceTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableDisableServiceTypeRequest.ProtoReflect.Descriptor instead.
func (*EnableDisableServiceTypeRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{21}
}

func (x *EnableDisableServiceTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnableDisableServiceTypeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EnableDisableServiceTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *EnableDisableServiceTypeResponse) Reset() {
	*x = EnableDisableServiceTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_service_type_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableDisableServiceTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableDisableServiceTypeResponse) ProtoMessage() {}

func (x *EnableDisableServiceTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_type_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableDisableServiceTypeResponse.ProtoReflect.Descriptor instead.
func (*EnableDisableServiceTypeResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_type_proto_rawDescGZIP(), []int{22}
}

func (x *EnableDisableServiceTypeResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EnableDisableServiceTypeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_transaction_service_type_proto protoreflect.FileDescriptor

var file_transaction_service_type_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x16, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x6f, 0x72, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x62, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x62, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x4d, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x8d, 0x01, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x4d, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x2e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x4d, 0x0a, 0x1d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x4d, 0x0a, 0x23, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x54,
	0x0a, 0x24, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0xed, 0x02, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x61, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62,
	0x61, 0x73, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x73,
	0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69,
	0x6e, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09,
	0x6d, 0x69, 0x6e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x2f, 0x0a, 0x14, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x6f, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x6e, 0x41, 0x64, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x3f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x29, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x7a, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x2f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x9f, 0x02, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x61, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x61,
	0x73, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x73, 0x74,
	0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65,
	0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e,
	0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6d,
	0x69, 0x6e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x2f,
	0x0a, 0x14, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f,
	0x6f, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x6e, 0x41, 0x64, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x7a, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2f, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xe5,
	0x03, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x61, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62,
	0x61, 0x73, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x73,
	0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69,
	0x6e, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09,
	0x6d, 0x69, 0x6e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x2f, 0x0a, 0x14, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x6f, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x6e, 0x41, 0x64, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62,
	0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x35, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x77, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7d, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0xc0, 0x01, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x12, 0x3a, 0x0a, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x12, 0x2c, 0x0a, 0x04,
	0x73, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x17, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x2f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x2a, 0x0a, 0x18, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x49, 0x0a, 0x1f, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x50, 0x0a,
	0x20, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42,
	0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transaction_service_type_proto_rawDescOnce sync.Once
	file_transaction_service_type_proto_rawDescData = file_transaction_service_type_proto_rawDesc
)

func file_transaction_service_type_proto_rawDescGZIP() []byte {
	file_transaction_service_type_proto_rawDescOnce.Do(func() {
		file_transaction_service_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_transaction_service_type_proto_rawDescData)
	})
	return file_transaction_service_type_proto_rawDescData
}

var file_transaction_service_type_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_transaction_service_type_proto_goTypes = []interface{}{
	(*GetServiceTypeItem)(nil),                   // 0: transaction.GetServiceTypeItem
	(*CreateServiceTypeItemRequest)(nil),         // 1: transaction.CreateServiceTypeItemRequest
	(*CreateServiceTypeItemResponse)(nil),        // 2: transaction.CreateServiceTypeItemResponse
	(*UpdateServiceTypeItemRequest)(nil),         // 3: transaction.UpdateServiceTypeItemRequest
	(*UpdateServiceTypeItemResponse)(nil),        // 4: transaction.UpdateServiceTypeItemResponse
	(*DeleteServiceTypeItemRequest)(nil),         // 5: transaction.DeleteServiceTypeItemRequest
	(*DeleteServiceTypeItemResponse)(nil),        // 6: transaction.DeleteServiceTypeItemResponse
	(*EnableDisableServiceTypeItemRequest)(nil),  // 7: transaction.EnableDisableServiceTypeItemRequest
	(*EnableDisableServiceTypeItemResponse)(nil), // 8: transaction.EnableDisableServiceTypeItemResponse
	(*CreateServiceTypeRequest)(nil),             // 9: transaction.CreateServiceTypeRequest
	(*CreateServiceTypeResponse)(nil),            // 10: transaction.CreateServiceTypeResponse
	(*UpdateServiceTypeRequest)(nil),             // 11: transaction.UpdateServiceTypeRequest
	(*UpdateServiceTypeResponse)(nil),            // 12: transaction.UpdateServiceTypeResponse
	(*GetServiceType)(nil),                       // 13: transaction.GetServiceType
	(*GetServiceTypeRequest)(nil),                // 14: transaction.GetServiceTypeRequest
	(*GetServiceTypeResponse)(nil),               // 15: transaction.GetServiceTypeResponse
	(*ListServiceTypeFilter)(nil),                // 16: transaction.ListServiceTypeFilter
	(*ListServiceTypeRequest)(nil),               // 17: transaction.ListServiceTypeRequest
	(*ListServiceTypeResponse)(nil),              // 18: transaction.ListServiceTypeResponse
	(*DeleteServiceTypeRequest)(nil),             // 19: transaction.DeleteServiceTypeRequest
	(*DeleteServiceTypeResponse)(nil),            // 20: transaction.DeleteServiceTypeResponse
	(*EnableDisableServiceTypeRequest)(nil),      // 21: transaction.EnableDisableServiceTypeRequest
	(*EnableDisableServiceTypeResponse)(nil),     // 22: transaction.EnableDisableServiceTypeResponse
	(*SortRequest)(nil),                          // 23: transaction.SortRequest
}
var file_transaction_service_type_proto_depIdxs = []int32{
	0,  // 0: transaction.CreateServiceTypeItemRequest.data:type_name -> transaction.GetServiceTypeItem
	0,  // 1: transaction.UpdateServiceTypeItemRequest.data:type_name -> transaction.GetServiceTypeItem
	1,  // 2: transaction.CreateServiceTypeRequest.items:type_name -> transaction.CreateServiceTypeItemRequest
	13, // 3: transaction.CreateServiceTypeResponse.data:type_name -> transaction.GetServiceType
	13, // 4: transaction.UpdateServiceTypeResponse.data:type_name -> transaction.GetServiceType
	0,  // 5: transaction.GetServiceType.items:type_name -> transaction.GetServiceTypeItem
	13, // 6: transaction.GetServiceTypeResponse.data:type_name -> transaction.GetServiceType
	16, // 7: transaction.ListServiceTypeRequest.filter:type_name -> transaction.ListServiceTypeFilter
	23, // 8: transaction.ListServiceTypeRequest.sort:type_name -> transaction.SortRequest
	13, // 9: transaction.ListServiceTypeResponse.data:type_name -> transaction.GetServiceType
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_transaction_service_type_proto_init() }
func file_transaction_service_type_proto_init() {
	if File_transaction_service_type_proto != nil {
		return
	}
	file_transaction_sort_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_transaction_service_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServiceTypeItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServiceTypeItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServiceTypeItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServiceTypeItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServiceTypeItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteServiceTypeItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteServiceTypeItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableDisableServiceTypeItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableDisableServiceTypeItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServiceTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServiceTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServiceTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServiceTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServiceType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServiceTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServiceTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListServiceTypeFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListServiceTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListServiceTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteServiceTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteServiceTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableDisableServiceTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_service_type_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableDisableServiceTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transaction_service_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_service_type_proto_goTypes,
		DependencyIndexes: file_transaction_service_type_proto_depIdxs,
		MessageInfos:      file_transaction_service_type_proto_msgTypes,
	}.Build()
	File_transaction_service_type_proto = out.File
	file_transaction_service_type_proto_rawDesc = nil
	file_transaction_service_type_proto_goTypes = nil
	file_transaction_service_type_proto_depIdxs = nil
}
