// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.3
// source: transaction/transaction.proto

package transaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionServiceClient interface {
	// Service Type
	CreateServiceType(ctx context.Context, in *CreateServiceTypeRequest, opts ...grpc.CallOption) (*CreateServiceTypeResponse, error)
	UpdateServiceType(ctx context.Context, in *UpdateServiceTypeRequest, opts ...grpc.CallOption) (*UpdateServiceTypeResponse, error)
	GetServiceType(ctx context.Context, in *GetServiceTypeRequest, opts ...grpc.CallOption) (*GetServiceTypeResponse, error)
	ListServiceType(ctx context.Context, in *ListServiceTypeRequest, opts ...grpc.CallOption) (*ListServiceTypeResponse, error)
	DeleteServiceType(ctx context.Context, in *DeleteServiceTypeRequest, opts ...grpc.CallOption) (*DeleteServiceTypeResponse, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) CreateServiceType(ctx context.Context, in *CreateServiceTypeRequest, opts ...grpc.CallOption) (*CreateServiceTypeResponse, error) {
	out := new(CreateServiceTypeResponse)
	err := c.cc.Invoke(ctx, "/transaction.TransactionService/CreateServiceType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) UpdateServiceType(ctx context.Context, in *UpdateServiceTypeRequest, opts ...grpc.CallOption) (*UpdateServiceTypeResponse, error) {
	out := new(UpdateServiceTypeResponse)
	err := c.cc.Invoke(ctx, "/transaction.TransactionService/UpdateServiceType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetServiceType(ctx context.Context, in *GetServiceTypeRequest, opts ...grpc.CallOption) (*GetServiceTypeResponse, error) {
	out := new(GetServiceTypeResponse)
	err := c.cc.Invoke(ctx, "/transaction.TransactionService/GetServiceType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ListServiceType(ctx context.Context, in *ListServiceTypeRequest, opts ...grpc.CallOption) (*ListServiceTypeResponse, error) {
	out := new(ListServiceTypeResponse)
	err := c.cc.Invoke(ctx, "/transaction.TransactionService/ListServiceType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) DeleteServiceType(ctx context.Context, in *DeleteServiceTypeRequest, opts ...grpc.CallOption) (*DeleteServiceTypeResponse, error) {
	out := new(DeleteServiceTypeResponse)
	err := c.cc.Invoke(ctx, "/transaction.TransactionService/DeleteServiceType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
// All implementations must embed UnimplementedTransactionServiceServer
// for forward compatibility
type TransactionServiceServer interface {
	// Service Type
	CreateServiceType(context.Context, *CreateServiceTypeRequest) (*CreateServiceTypeResponse, error)
	UpdateServiceType(context.Context, *UpdateServiceTypeRequest) (*UpdateServiceTypeResponse, error)
	GetServiceType(context.Context, *GetServiceTypeRequest) (*GetServiceTypeResponse, error)
	ListServiceType(context.Context, *ListServiceTypeRequest) (*ListServiceTypeResponse, error)
	DeleteServiceType(context.Context, *DeleteServiceTypeRequest) (*DeleteServiceTypeResponse, error)
	mustEmbedUnimplementedTransactionServiceServer()
}

// UnimplementedTransactionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTransactionServiceServer struct {
}

func (UnimplementedTransactionServiceServer) CreateServiceType(context.Context, *CreateServiceTypeRequest) (*CreateServiceTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServiceType not implemented")
}
func (UnimplementedTransactionServiceServer) UpdateServiceType(context.Context, *UpdateServiceTypeRequest) (*UpdateServiceTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServiceType not implemented")
}
func (UnimplementedTransactionServiceServer) GetServiceType(context.Context, *GetServiceTypeRequest) (*GetServiceTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceType not implemented")
}
func (UnimplementedTransactionServiceServer) ListServiceType(context.Context, *ListServiceTypeRequest) (*ListServiceTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServiceType not implemented")
}
func (UnimplementedTransactionServiceServer) DeleteServiceType(context.Context, *DeleteServiceTypeRequest) (*DeleteServiceTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteServiceType not implemented")
}
func (UnimplementedTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {}

// UnsafeTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServiceServer will
// result in compilation errors.
type UnsafeTransactionServiceServer interface {
	mustEmbedUnimplementedTransactionServiceServer()
}

func RegisterTransactionServiceServer(s grpc.ServiceRegistrar, srv TransactionServiceServer) {
	s.RegisterService(&TransactionService_ServiceDesc, srv)
}

func _TransactionService_CreateServiceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CreateServiceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.TransactionService/CreateServiceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CreateServiceType(ctx, req.(*CreateServiceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_UpdateServiceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).UpdateServiceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.TransactionService/UpdateServiceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).UpdateServiceType(ctx, req.(*UpdateServiceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetServiceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetServiceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.TransactionService/GetServiceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetServiceType(ctx, req.(*GetServiceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ListServiceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ListServiceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.TransactionService/ListServiceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ListServiceType(ctx, req.(*ListServiceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_DeleteServiceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServiceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).DeleteServiceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.TransactionService/DeleteServiceType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).DeleteServiceType(ctx, req.(*DeleteServiceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionService_ServiceDesc is the grpc.ServiceDesc for TransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateServiceType",
			Handler:    _TransactionService_CreateServiceType_Handler,
		},
		{
			MethodName: "UpdateServiceType",
			Handler:    _TransactionService_UpdateServiceType_Handler,
		},
		{
			MethodName: "GetServiceType",
			Handler:    _TransactionService_GetServiceType_Handler,
		},
		{
			MethodName: "ListServiceType",
			Handler:    _TransactionService_ListServiceType_Handler,
		},
		{
			MethodName: "DeleteServiceType",
			Handler:    _TransactionService_DeleteServiceType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction/transaction.proto",
}
